import type { Metadata, Viewport } from 'next'
import './globals.css'
import Navigation from '@modules/Navigation'

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="bg-cream text-tea">
        <Navigation />
        {children}
      </body>
    </html>
  )
}
